/**
 * SPIN SERVICE - Spin Management
 *
 * Handles all spin-related operations:
 * - Adding/removing spins
 * - Executing spins with custom outcome
 * - Reward calculation
 * - Prison penalty
 */

import { getPlayer, savePlayer } from './playerCoreService';
import { Players } from '@/entities';

type SymbolType = '💎' | '💵' | '🔫' | '🚔';

type SpinResultType = 'jackpot' | 'money' | 'attack' | 'prison' | 'none';

export interface SpinOperationResult {
  type: SpinResultType;
  amount: number;
  updatedPlayer: Players;
}

function isTriple(outcome: SymbolType[], symbol: SymbolType) {
  return outcome.length === 3 && outcome.every((item) => item === symbol);
}

/**
 * Add spins to player
 */
export async function addSpins(playerId: string, amount: number): Promise<Players> {
  const player = await getPlayer(playerId);
  if (!player) throw new Error(`Player ${playerId} not found`);

  const updated: Players = {
    ...player,
    spins: (player.spins ?? 0) + amount,
  };

  return savePlayer(updated);
}

/**
 * Remove spins from player
 * Throws error if insufficient spins
 */
export async function removeSpins(playerId: string, amount: number): Promise<Players> {
  const player = await getPlayer(playerId);
  if (!player) throw new Error(`Player ${playerId} not found`);

  const currentSpins = player.spins ?? 0;

  if (currentSpins < amount) {
    throw new Error(`Insufficient spins. Have: ${currentSpins}, Need: ${amount}`);
  }

  const updated: Players = {
    ...player,
    spins: currentSpins - amount,
  };

  return savePlayer(updated);
}

/**
 * Execute full spin operation using the visual outcome generated by SlotMachine
 *
 * Rules:
 * - Always costs 1 spin
 * - 💎💎💎 = jackpot
 * - 💵💵💵 = money
 * - 🔫🔫🔫 = attack reward (money reward for now)
 * - 🚔🚔🚔 = prison penalty (lose 30% dirty money)
 * - everything else = no reward
 */
export async function executeSpinOperation(
  playerId: string,
  outcome: SymbolType[],
  multiplier: number = 1
): Promise<SpinOperationResult> {
  const player = await getPlayer(playerId);
  if (!player) throw new Error(`Player ${playerId} not found`);

  const currentSpins = player.spins ?? 0;
  const currentDirtyMoney = player.dirtyMoney ?? 0;

  if (currentSpins <= 0) {
    throw new Error('No spins available');
  }

  const safeMultiplier = Math.max(1, multiplier);

  let type: SpinResultType = 'none';
  let amount = 0;

  let updatedPlayer: Players = {
    ...player,
    spins: currentSpins - 1,
  };

  if (isTriple(outcome, '💎')) {
    type = 'jackpot';
    amount = 5000 * safeMultiplier;

    updatedPlayer = {
      ...updatedPlayer,
      dirtyMoney: currentDirtyMoney + amount,
    };
  } else if (isTriple(outcome, '💵')) {
    type = 'money';
    amount = 1000 * safeMultiplier;

    updatedPlayer = {
      ...updatedPlayer,
      dirtyMoney: currentDirtyMoney + amount,
    };
  } else if (isTriple(outcome, '🔫')) {
    type = 'attack';
    amount = 1500 * safeMultiplier;

    updatedPlayer = {
      ...updatedPlayer,
      dirtyMoney: currentDirtyMoney + amount,
    };
  } else if (isTriple(outcome, '🚔')) {
    type = 'prison';
    amount = Math.floor(currentDirtyMoney * 0.3);

    updatedPlayer = {
      ...updatedPlayer,
      dirtyMoney: Math.max(0, currentDirtyMoney - amount),
    };
  } else {
    type = 'none';
    amount = 0;
  }

  const savedPlayer = await savePlayer(updatedPlayer);

  return {
    type,
    amount,
    updatedPlayer: savedPlayer,
  };
}

/**
 * Legacy/simple executeSpin
 * Kept for compatibility with older screens/components
 */
function calculateSpinReward(): { money: number; bonusSpins: number } {
  const baseReward = Math.floor(Math.random() * 500) + 100;
  const bonusSpins = Math.random() > 0.8 ? 1 : 0;

  return {
    money: baseReward,
    bonusSpins,
  };
}

export async function executeSpin(playerId: string): Promise<{
  player: Players;
  reward: { money: number; bonusSpins: number };
}> {
  const player = await getPlayer(playerId);
  if (!player) throw new Error(`Player ${playerId} not found`);

  const currentSpins = player.spins ?? 0;
  if (currentSpins <= 0) {
    throw new Error('No spins available');
  }

  const reward = calculateSpinReward();

  let updated: Players = {
    ...player,
    spins: currentSpins - 1,
    dirtyMoney: (player.dirtyMoney ?? 0) + reward.money,
  };

  if (reward.bonusSpins > 0) {
    updated = {
      ...updated,
      spins: updated.spins + reward.bonusSpins,
    };
  }

  const savedPlayer = await savePlayer(updated);

  return {
    player: savedPlayer,
    reward,
  };
}

/**
 * Get player's spin count
 */
export async function getSpinCount(playerId: string): Promise<number> {
  const player = await getPlayer(playerId);
  if (!player) throw new Error(`Player ${playerId} not found`);

  return player.spins ?? 0;
}