import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Image } from '@/components/ui/image';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import BlingModal from '@/components/BlingModal';
import LuxuryNPCDialog from '@/components/LuxuryNPCDialog';
import { usePlayerStore } from '@/store/playerStore';

// ✅ IMPORT CORRETO BASEADO NA SUA PASTA
import { getLuxurySystem } from '../data/luxoItems';

export default function LuxuryShowroomPage() {
  const [showItemsModal, setShowItemsModal] = useState(false);
    const [showInitialDialog, setShowInitialDialog] = useState(false);
      const [showCollectionModal, setShowCollectionModal] = useState(false);

        const barracoLevel = usePlayerStore((state) => state.barracoLevel);

          // 🔥 SISTEMA (SE DER ERRO NÃO QUEBRA A PÁGINA)
            let system;
              try {
                  system = getLuxurySystem(barracoLevel);
                    } catch (e) {
                        system = {
                              items: [],
                                    background: 'black',
                                          collectionName: 'Básico',
                                              };
                                                }

                                                  useEffect(() => {
                                                      const timer = setTimeout(() => {
                                                            setShowInitialDialog(true);
                                                                }, 2000);
                                                                    return () => clearTimeout(timer);
                                                                      }, []);

                                                                        return (
                                                                            <div className="flex flex-col min-h-screen">
                                                                                  <Header />

                                                                                        <div className="flex-1 relative w-full overflow-hidden bg-black">

                                                                                                {/* BACKGROUND BASE */}
                                                                                                        <Image
                                                                                                                  src="https://static.wixstatic.com/media/50f4bf_e591cecf171a471cbfa4c0d91653f072~mv2.png"
                                                                                                                            alt="Luxury Showroom"
                                                                                                                                      className="absolute w-full h-full object-cover"
                                                                                                                                                width={1920}
                                                                                                                                                          height={1080}
                                                                                                                                                                  />

                                                                                                                                                                          {/* BACKGROUND DINÂMICO */}
                                                                                                                                                                                  <div
                                                                                                                                                                                            className="absolute w-full h-full transition-all duration-700"
                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                  background: system.background,
                                                                                                                                                                                                                              opacity: 0.4,
                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                        {/* NPC */}
                                                                                                                                                                                                                                                                <motion.div
                                                                                                                                                                                                                                                                          className="absolute right-10 bottom-0 h-[80%] cursor-pointer"
                                                                                                                                                                                                                                                                                    animate={{
                                                                                                                                                                                                                                                                                                scale: [1, 1.03, 1],
                                                                                                                                                                                                                                                                                                            y: [0, -5, 0],
                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                transition={{
                                                                                                                                                                                                                                                                                                                                            duration: 4,
                                                                                                                                                                                                                                                                                                                                                        repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setShowItemsModal(true)}
                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                              <Image
                                                                                                                                                                                                                                                                                                                                                                                                          src="https://static.wixstatic.com/media/50f4bf_8dc3c6fde14f4e06b7937591bf2c203d~mv2.png"
                                                                                                                                                                                                                                                                                                                                                                                                                      alt="NPC"
                                                                                                                                                                                                                                                                                                                                                                                                                                  className="h-full drop-shadow-[0_0_25px_gold]"
                                                                                                                                                                                                                                                                                                                                                                                                                                              width={400}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          height={800}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* DIALOG */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <LuxuryNPCDialog
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      isOpen={showInitialDialog}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClose={() => setShowInitialDialog(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onViewCollection={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setShowInitialDialog(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setShowCollectionModal(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onAccept={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setShowInitialDialog(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setShowCollectionModal(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onDenounce={() => setShowInitialDialog(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title={`Coleção ${system.collectionName}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      message="Bem-vindo… Aqui não é sobre comprar. É sobre se posicionar. Cada coleção revela o seu nível. Escolha com cuidado… porque aqui, status é tudo."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* MODAL 1 */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <BlingModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        isOpen={showCollectionModal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClose={() => setShowCollectionModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onOk={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setShowCollectionModal(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setShowItemsModal(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onCancel={() => setShowCollectionModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title={`Coleção ${system.collectionName} 💎`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-center text-white mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-lg opacity-80">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Itens exclusivos para quem alcançou este nível...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </BlingModal>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* MODAL 2 */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <BlingModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      isOpen={showItemsModal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClose={() => setShowItemsModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onOk={() => setShowItemsModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onCancel={() => setShowItemsModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title={`Seleção ${system.collectionName} 💎`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="absolute inset-0 rounded-xl opacity-30"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ background: system.background }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="relative grid grid-cols-3 gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {system.items.map((item, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={index}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      whileHover={{ scale: 1.08 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="relative p-4 rounded-xl text-center backdrop-blur-md border border-yellow-400/30"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "linear-gradient(180deg, rgba(255,215,0,0.1), rgba(0,0,0,0.6))",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="absolute inset-0 rounded-xl shadow-[0_0_25px_rgba(255,215,0,0.3)]" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="relative h-20 flex items-center justify-center mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-3xl animate-pulse">💎</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-white/90">{item.name}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-yellow-400 font-bold text-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              R$ {item.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="mt-3 w-full bg-gradient-to-r from-yellow-400 to-yellow-600 hover:from-yellow-300 hover:to-yellow-500 text-black py-2 rounded-lg font-bold shadow-lg hover:shadow-yellow-500/50 transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Comprar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </BlingModal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
