import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Image } from '@/components/ui/image';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import BlingModal from '@/components/BlingModal';
import LuxuryNPCDialog from '@/components/LuxuryNPCDialog';
import { usePlayerStore } from '@/store/playerStore';

// ✅ NOVO IMPORT
import { getLuxurySystem } from '../../data/luxoItems';

export default function LuxuryShowroomPage() {
  const [showItemsModal, setShowItemsModal] = useState(false);
    const [showInitialDialog, setShowInitialDialog] = useState(false);
      const [showCollectionModal, setShowCollectionModal] = useState(false);

        // Get player's barraco level and player level from store
          const barracoLevel = usePlayerStore((state) => state.barracoLevel);
            const playerLevel = usePlayerStore((state) => state.level);

              // Show initial dialog after 2 seconds
                useEffect(() => {
                    const timer = setTimeout(() => {
                          setShowInitialDialog(true);
                              }, 2000);
                                  return () => clearTimeout(timer);
                                    }, []);

                                      // ✅ LÓGICA AJUSTADA (base no nível do barraco)
                                        const system = getLuxurySystem(barracoLevel || 1);

                                          const items = (system?.items || []).map((item, index) => ({
                                              id: index,
                                                  name: item.name,
                                                      price: item.price,
                                                        }));

                                                          return (
                                                              <div className="flex flex-col min-h-screen">
                                                                    <Header />
                                                                          <div className="flex-1 relative w-full overflow-hidden bg-black">

                                                                                  {/* BACKGROUND */}
                                                                                          <Image
                                                                                                    src="https://static.wixstatic.com/media/50f4bf_e591cecf171a471cbfa4c0d91653f072~mv2.png"
                                                                                                              alt="Luxury Showroom Background"
                                                                                                                        className="absolute w-full h-full object-cover"
                                                                                                                                  width={1920}
                                                                                                                                            height={1080}
                                                                                                                                                    />

                                                                                                                                                            {/* NPC 2D */}
                                                                                                                                                                    <Image
                                                                                                                                                                              src="https://static.wixstatic.com/media/50f4bf_8dc3c6fde14f4e06b7937591bf2c203d~mv2.png"
                                                                                                                                                                                        alt="NPC"
                                                                                                                                                                                                  onClick={() => setShowItemsModal(true)}
                                                                                                                                                                                                            className="absolute right-10 bottom-0 h-[80%] cursor-pointer transition-transform hover:scale-105"
                                                                                                                                                                                                                      width={400}
                                                                                                                                                                                                                                height={800}
                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                {/* LUXURY NPC DIALOG */}
                                                                                                                                                                                                                                                        <LuxuryNPCDialog
                                                                                                                                                                                                                                                                  isOpen={showInitialDialog}
                                                                                                                                                                                                                                                                            onClose={() => setShowInitialDialog(false)}
                                                                                                                                                                                                                                                                                      onViewCollection={() => {
                                                                                                                                                                                                                                                                                                  setShowInitialDialog(false);
                                                                                                                                                                                                                                                                                                              setShowCollectionModal(true);
                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                  onAccept={() => {
                                                                                                                                                                                                                                                                                                                                              setShowInitialDialog(false);
                                                                                                                                                                                                                                                                                                                                                          setShowCollectionModal(true);
                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                              onDenounce={() => {
                                                                                                                                                                                                                                                                                                                                                                                          setShowInitialDialog(false);
                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                              title="Bem-vindo ao Showroom"
                                                                                                                                                                                                                                                                                                                                                                                                                        message="Bem-vindo… Aqui não é sobre comprar. É sobre se posicionar. Cada coleção revela o seu nível. Escolha com cuidado… porque aqui, status é tudo."
                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* BLING COLLECTION MODAL */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                <BlingModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                          isOpen={showCollectionModal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClose={() => setShowCollectionModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onOk={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setShowCollectionModal(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setShowItemsModal(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onCancel={() => setShowCollectionModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onHelp={() => alert('Bem-vindo à coleção exclusiva de luxo!')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title={`Coleção Nível ${barracoLevel} 💎`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-center text-white/80 font-paragraph mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Selecione os itens que deseja adquirir para elevar seu status...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Aqui você pode renderizar os itens se quiser */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {items.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={item.id} className="p-4 bg-white/10 rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-white font-bold">{item.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-white/70">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      R$ {item.price.toLocaleString('pt-BR')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </BlingModal>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
