import BlingModal from '@/components/BlingModal';
import CreditCardPurchaseAnimation from '@/components/CreditCardPurchaseAnimation';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import LiveNPC from '@/components/LiveNPC';
import Luxury3DShowroom from '@/components/Luxury3DShowroom';
import LuxuryNPCDialog from '@/components/LuxuryNPCDialog';
import { Image } from '@/components/ui/image';
import { Players } from '@/entities';
import { BaseCrudService } from '@/integrations';
import { useCleanMoneyStore } from '@/store/cleanMoneyStore';
import { usePlayerStore } from '@/store/playerStore';
import { useEffect, useState } from 'react';

import { getBackgroundByLevel, getLuxurySystem } from '../../data/luxoItems';

export default function LuxuryShowroomPage() {
  const [showItemsModal, setShowItemsModal] = useState(false);
    const [showInitialDialog, setShowInitialDialog] = useState(true); // 🔥 FORÇADO PRA FUNCIONAR
      const [showCollectionModal, setShowCollectionModal] = useState(false);
        const [purchaseMessage, setPurchaseMessage] = useState('');
          const [loading, setLoading] = useState(true);
            const [purchasedItems, setPurchasedItems] = useState<Set<number>>(new Set());
              const [showCardAnimation, setShowCardAnimation] = useState(false);
                const [animatingItem, setAnimatingItem] = useState<{ name: string; price: number } | null>(null);

                  const barracoLevel = usePlayerStore((state) => state.barracoLevel);
                    const playerLevel = usePlayerStore((state) => state.level);
                      const cleanMoney = useCleanMoneyStore((state) => state.cleanMoney);
                        const removeCleanMoney = useCleanMoneyStore((state) => state.removeCleanMoney);
                          const { setBarracoLevel } = usePlayerStore();

                            useEffect(() => {
                                const loadPlayerData = async () => {
                                      try {
                                              const urlParams = new URLSearchParams(window.location.search);
                                                      let playerId = urlParams.get('playerId') || localStorage.getItem('currentPlayerId');

                                                                      if (!playerId) {
                                                                                const result = await BaseCrudService.getAll<Players>('players', [], { limit: 1 });
                                                                                          if (result.items && result.items.length > 0) {
                                                                                                      playerId = result.items[0]._id;
                                                                                                                  localStorage.setItem('currentPlayerId', playerId);
                                                                                                                            }
                                                                                                                                    }

                                                                                                                                            if (playerId) {
                                                                                                                                                      const playerData = await BaseCrudService.getById<Players>('players', playerId);
                                                                                                                                                                if (playerData?.level) {
                                                                                                                                                                            setBarracoLevel(playerData.level);
                                                                                                                                                                                      }
                                                                                                                                                                                              }
                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                            console.error('Erro ao carregar dados do jogador:', err);
                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                        loadPlayerData();
                                                                                                                                                                                                                                          }, [setBarracoLevel]);

                                                                                                                                                                                                                                            const level = barracoLevel ?? 1;
                                                                                                                                                                                                                                              const system = getLuxurySystem(level);

                                                                                                                                                                                                                                                const items = (system?.items || []).map((item, index) => ({
                                                                                                                                                                                                                                                    id: index,
                                                                                                                                                                                                                                                        name: item.name,
                                                                                                                                                                                                                                                            price: item.price,
                                                                                                                                                                                                                                                                image: item.image,
                                                                                                                                                                                                                                                                  }));

                                                                                                                                                                                                                                                                    // 🔥 mantém o delay mas não depende dele pra aparecer
                                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                                          const timer = setTimeout(() => {
                                                                                                                                                                                                                                                                                setShowInitialDialog(true);
                                                                                                                                                                                                                                                                                    }, 2000);
                                                                                                                                                                                                                                                                                        return () => clearTimeout(timer);
                                                                                                                                                                                                                                                                                          }, []);

                                                                                                                                                                                                                                                                                            const handleBuyItem = (item: any, itemIndex: number) => {
                                                                                                                                                                                                                                                                                                if (purchasedItems.has(itemIndex)) {
                                                                                                                                                                                                                                                                                                      setPurchaseMessage(`❌ Este item já foi comprado!`);
                                                                                                                                                                                                                                                                                                            setTimeout(() => setPurchaseMessage(''), 3000);
                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                          if (cleanMoney >= item.price) {
                                                                                                                                                                                                                                                                                                                                setAnimatingItem({ name: item.name, price: item.price });
                                                                                                                                                                                                                                                                                                                                      setShowCardAnimation(true);

                                                                                                                                                                                                                                                                                                                                                  setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                          removeCleanMoney(item.price);
                                                                                                                                                                                                                                                                                                                                                                  setPurchasedItems(new Set(purchasedItems).add(itemIndex));
                                                                                                                                                                                                                                                                                                                                                                          setPurchaseMessage(`✅ ${item.name} comprado com sucesso!`);
                                                                                                                                                                                                                                                                                                                                                                                  setTimeout(() => setPurchaseMessage(''), 3000);
                                                                                                                                                                                                                                                                                                                                                                                        }, 5000);
                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                  setPurchaseMessage(`❌ Dinheiro insuficiente!`);
                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(() => setPurchaseMessage(''), 3000);
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex flex-col min-h-screen">
                                                                                                                                                                                                                                                                                                                                                                                                                          <Header />

                                                                                                                                                                                                                                                                                                                                                                                                                                {animatingItem && (
                                                                                                                                                                                                                                                                                                                                                                                                                                        <CreditCardPurchaseAnimation
                                                                                                                                                                                                                                                                                                                                                                                                                                                  isVisible={showCardAnimation}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            itemName={animatingItem.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      price={animatingItem.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onComplete={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setShowCardAnimation(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setAnimatingItem(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex-1 relative w-full overflow-hidden" style={{ background: getBackgroundByLevel(level) }}>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="absolute inset-0 w-full h-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Luxury3DShowroom />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  src="https://static.wixstatic.com/media/50f4bf_e591cecf171a471cbfa4c0d91653f072~mv2.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alt="Luxury Showroom Background"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="absolute w-full h-full object-cover opacity-30"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width={1920}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height={1080}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="absolute right-10 bottom-0 h-[80%] z-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <LiveNPC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src="https://static.wixstatic.com/media/50f4bf_8dc3c6fde14f4e06b7937591bf2c203d~mv2.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alt="NPC"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setShowItemsModal(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="absolute right-0 bottom-0 h-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width={400}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            height={800}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* 🔥 DIÁLOGO FUNCIONANDO */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <LuxuryNPCDialog
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        isOpen={showInitialDialog}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClose={() => setShowInitialDialog(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onViewCollection={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setShowInitialDialog(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setShowCollectionModal(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Bem-vindo ao Showroom"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  message="Aqui não é sobre comprar. É sobre se posicionar."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <BlingModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isOpen={showCollectionModal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClose={() => setShowCollectionModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title={`Coleção ${system.collectionName}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {items.map((item, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={item.id} className="flex justify-between text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>{item.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => handleBuyItem(item, index)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Comprar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </BlingModal>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
