import { useEffect, useRef } from 'react';
import * as THREE from 'three';

export default function CinematicSignboard() {
  const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!containerRef.current) return;

            const scene = new THREE.Scene();
                scene.background = new THREE.Color(0x020205); // Preto mais imersivo
                    scene.fog = new THREE.Fog(0x020205, 50, 400);

                        const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
                            // Ponto inicial bem longe para o zoom ter impacto
                                camera.position.set(0, 20, 180);

                                    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
                                        renderer.setSize(window.innerWidth, window.innerHeight);
                                            renderer.setPixelRatio(window.devicePixelRatio);
                                                containerRef.current.appendChild(renderer.domElement);

                                                    const ambientLight = new THREE.AmbientLight(0xffffff, 0.4);
                                                        scene.add(ambientLight);

                                                            // Spotlight Dourado focado no letreiro
                                                                const spotLight = new THREE.SpotLight(0xffd700, 5, 250, Math.PI / 4, 0.5, 1);
                                                                    spotLight.position.set(0, 50, 40);
                                                                        scene.add(spotLight);

                                                                            // Neon de "Perigo/Comando"
                                                                                const neonLight = new THREE.PointLight(0x00eaff, 2, 150);
                                                                                    neonLight.position.set(0, -10, 15);
                                                                                        scene.add(neonLight);

                                                                                            const signboard = new THREE.Group();
                                                                                                scene.add(signboard);

                                                                                                    const canvas = document.createElement('canvas');
                                                                                                        canvas.width = 2048;
                                                                                                            canvas.height = 512;
                                                                                                                const ctx = canvas.getContext('2d');
                                                                                                                    if (ctx) {
                                                                                                                          ctx.fillStyle = '#050505';
                                                                                                                                ctx.fillRect(0, 0, canvas.width, canvas.height);

                                                                                                                                      // Fonte Industrial Pesada
                                                                                                                                            ctx.font = '900 165px "Impact", "Arial Black", sans-serif';
                                                                                                                                                  ctx.textAlign = 'center';
                                                                                                                                                        ctx.textBaseline = 'middle';

                                                                                                                                                              // Gradiente de Ouro Puro
                                                                                                                                                                    const grad = ctx.createLinearGradient(0, 120, 0, 380);
                                                                                                                                                                          grad.addColorStop(0, '#fff3a0'); // Brilho topo
                                                                                                                                                                                grad.addColorStop(0.5, '#ffd700'); // Ouro
                                                                                                                                                                                      grad.addColorStop(1, '#8a6d3b'); // Sombra metal

                                                                                                                                                                                                  ctx.shadowColor = '#00eaff';
                                                                                                                                                                                                        ctx.shadowBlur = 35; // Brilho neon em volta do ouro
                                                                                                                                                                                                              ctx.fillStyle = grad;
                                                                                                                                                                                                                    ctx.fillText('COMPLEXO 1 DO COMANDO NORTE', canvas.width / 2, canvas.height / 2);
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                            const texture = new THREE.CanvasTexture(canvas);
                                                                                                                                                                                                                                const material = new THREE.MeshStandardMaterial({
                                                                                                                                                                                                                                      map: texture,
                                                                                                                                                                                                                                            emissive: new THREE.Color(0xffd700),
                                                                                                                                                                                                                                                  emissiveIntensity: 0.5,
                                                                                                                                                                                                                                                        metalness: 1,
                                                                                                                                                                                                                                                              roughness: 0.1,
                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                      const mesh = new THREE.Mesh(new THREE.PlaneGeometry(50, 12), material);
                                                                                                                                                                                                                                                                          signboard.add(mesh);

                                                                                                                                                                                                                                                                              const frame = new THREE.Mesh(
                                                                                                                                                                                                                                                                                    new THREE.BoxGeometry(52, 14, 0.5),
                                                                                                                                                                                                                                                                                          new THREE.MeshStandardMaterial({ color: 0xffd700, metalness: 1, roughness: 0.1 })
                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                  frame.position.z = -0.2;
                                                                                                                                                                                                                                                                                                      signboard.add(frame);

                                                                                                                                                                                                                                                                                                          // Animação de Entrada
                                                                                                                                                                                                                                                                                                              const startTime = Date.now();
                                                                                                                                                                                                                                                                                                                  const zoomDuration = 2200; // 2.2 segundos de pura adrenalina

                                                                                                                                                                                                                                                                                                                      const animate = () => {
                                                                                                                                                                                                                                                                                                                            requestAnimationFrame(animate);
                                                                                                                                                                                                                                                                                                                                  const elapsed = Date.now() - startTime;

                                                                                                                                                                                                                                                                                                                                        if (elapsed < zoomDuration) {
                                                                                                                                                                                                                                                                                                                                                const progress = elapsed / zoomDuration;
                                                                                                                                                                                                                                                                                                                                                        // Curva de velocidade "voadora": começa rápido e trava no lugar
                                                                                                                                                                                                                                                                                                                                                                const ease = 1 - Math.pow(1 - progress, 4);
                                                                                                                                                                                                                                                                                                                                                                        camera.position.z = 180 - (ease * 145); // Voa de 180 para 35
                                                                                                                                                                                                                                                                                                                                                                                camera.position.y = 20 - (ease * 15);  // Ajusta altura
                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                              // Leve balanço de "câmera na mão" após o impacto
                                                                                                                                                                                                                                                                                                                                                                                                      camera.position.x = Math.sin(elapsed * 0.002) * 0.1;
                                                                                                                                                                                                                                                                                                                                                                                                              camera.position.y = 5 + Math.cos(elapsed * 0.002) * 0.1;
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                          // Rotação sutil e pulsação do Neon
                                                                                                                                                                                                                                                                                                                                                                                                                                signboard.rotation.y = Math.sin(elapsed * 0.001) * 0.03;
                                                                                                                                                                                                                                                                                                                                                                                                                                      neonLight.intensity = 1.5 + Math.sin(elapsed * 0.005) * 1.5;

                                                                                                                                                                                                                                                                                                                                                                                                                                            renderer.render(scene, camera);
                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate();

                                                                                                                                                                                                                                                                                                                                                                                                                                                        const handleResize = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              camera.aspect = window.innerWidth / window.innerHeight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    camera.updateProjectionMatrix();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          renderer.setSize(window.innerWidth, window.innerHeight);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.addEventListener('resize', handleResize);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.removeEventListener('resize', handleResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderer.dispose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return <div ref={containerRef} className="w-full h-full" style={{ background: '#000' }} />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          