import { Image } from '@/components/ui/image';
import { motion } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';

interface LiveNPCProps {
  src: string;
    alt: string;
      onClick?: () => void;
        className?: string;
          width?: number;
            height?: number;
            }

            export default function LiveNPC({
              src,
                alt,
                  onClick,
                    className = '',
                      width = 400,
                        height = 800,
                        }: LiveNPCProps) {
                          const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
                            const [isHovered, setIsHovered] = useState(false);
                              const [isPressed, setIsPressed] = useState(false);
                                const [blink, setBlink] = useState(false);

                                  const containerRef = useRef<HTMLDivElement>(null);

                                    // 👁️ BLINK
                                      useEffect(() => {
                                          let blinkTimeout: NodeJS.Timeout;
                                              let nextBlink: NodeJS.Timeout;

                                                  const schedule = () => {
                                                        const delay = Math.random() * 3000 + 3000;

                                                              nextBlink = setTimeout(() => {
                                                                      setBlink(true);

                                                                              blinkTimeout = setTimeout(() => {
                                                                                        setBlink(false);
                                                                                                  schedule();
                                                                                                          }, 120);
                                                                                                                }, delay);
                                                                                                                    };

                                                                                                                        schedule();

                                                                                                                            return () => {
                                                                                                                                  clearTimeout(blinkTimeout);
                                                                                                                                        clearTimeout(nextBlink);
                                                                                                                                            };
                                                                                                                                              }, []);

                                                                                                                                                // 👀 MOUSE TRACKING
                                                                                                                                                  useEffect(() => {
                                                                                                                                                      const handleMouseMove = (e: MouseEvent) => {
                                                                                                                                                            if (!containerRef.current) return;

                                                                                                                                                                  const rect = containerRef.current.getBoundingClientRect();

                                                                                                                                                                        const centerX = rect.left + rect.width / 2;
                                                                                                                                                                              const centerY = rect.top + rect.height / 2;

                                                                                                                                                                                    const deltaX = e.clientX - centerX;
                                                                                                                                                                                          const deltaY = e.clientY - centerY;

                                                                                                                                                                                                const distance = Math.sqrt(deltaX * deltaX + deltaY * deltaY);
                                                                                                                                                                                                      const maxDistance = Math.max(rect.width, rect.height);

                                                                                                                                                                                                            const maxOffset = 5;
                                                                                                                                                                                                                  const offset = Math.min((distance / maxDistance) * maxOffset, maxOffset);

                                                                                                                                                                                                                        const dirX = deltaX / distance || 0;
                                                                                                                                                                                                                              const dirY = deltaY / distance || 0;

                                                                                                                                                                                                                                    setMousePosition({
                                                                                                                                                                                                                                            x: dirX * offset * 0.4,
                                                                                                                                                                                                                                                    y: dirY * offset * 0.4,
                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                  window.addEventListener('mousemove', handleMouseMove);
                                                                                                                                                                                                                                                                      return () => window.removeEventListener('mousemove', handleMouseMove);
                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                          // 🌬️ RESPIRAÇÃO
                                                                                                                                                                                                                                                                            const breathing = {
                                                                                                                                                                                                                                                                                animate: {
                                                                                                                                                                                                                                                                                      y: [0, -1.5, 0],
                                                                                                                                                                                                                                                                                            transition: {
                                                                                                                                                                                                                                                                                                    duration: 5,
                                                                                                                                                                                                                                                                                                            ease: 'easeInOut',
                                                                                                                                                                                                                                                                                                                    repeat: Infinity,
                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                            ref={containerRef}
                                                                                                                                                                                                                                                                                                                                                  className="relative flex justify-center items-center"
                                                                                                                                                                                                                                                                                                                                                        style={{ width, height }}
                                                                                                                                                                                                                                                                                                                                                              onMouseEnter={() => setIsHovered(true)}
                                                                                                                                                                                                                                                                                                                                                                    onMouseLeave={() => {
                                                                                                                                                                                                                                                                                                                                                                            setIsHovered(false);
                                                                                                                                                                                                                                                                                                                                                                                    setIsPressed(false);
                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                onMouseDown={() => setIsPressed(true)}
                                                                                                                                                                                                                                                                                                                                                                                                      onMouseUp={() => setIsPressed(false)}
                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                <motion.div variants={breathing} animate="animate">
                                                                                                                                                                                                                                                                                                                                                                                                                        <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                  animate={{
                                                                                                                                                                                                                                                                                                                                                                                                                                              scale: isPressed ? 0.97 : isHovered ? 1.05 : 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          filter: isHovered ? 'brightness(1.08)' : 'brightness(1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      x: mousePosition.x,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  y: mousePosition.y,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition={{ duration: 0.3 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* SOMBRA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="absolute -bottom-6 left-1/2 -translate-x-1/2 w-3/4 h-6 rounded-full blur-2xl opacity-30"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'radial-gradient(ellipse, rgba(0,0,0,0.4), transparent)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* NPC */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            src={src}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alt={alt}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={onClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width={width}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    height={height}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`cursor-pointer ${className}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* BLINK */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {blink && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    initial={{ scaleY: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={{ scaleY: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transition={{ duration: 0.12 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="absolute left-1/2 -translate-x-1/2 pointer-events-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      top: '22%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: '35%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height: '12%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: 'rgba(0,0,0,0.6)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: '50%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transformOrigin: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
